# Generated by Django 2.2.2 on 2019-07-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='votes',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='create_by',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='update_date',
        ),
    ]
