# Generated by Django 2.2.2 on 2019-07-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20190705_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='voted_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
