# Generated by Django 2.2.2 on 2019-07-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_auto_20190705_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='mac_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
