# Generated by Django 2.2.2 on 2019-07-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_auto_20190708_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='short_desc',
        ),
    ]
