# Generated by Django 2.0 on 2019-07-19 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_sitesetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={},
        ),
    ]
