# Generated by Django 2.0 on 2019-07-20 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_auto_20190720_0021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSetting',
        ),
    ]
