# Generated by Django 2.0 on 2019-07-30 18:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0013_auto_20190721_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='long_desc',
            field=ckeditor.fields.RichTextField(verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
