# Generated by Django 2.0 on 2019-07-30 18:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0014_auto_20190731_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='short_desc',
            field=ckeditor.fields.RichTextField(verbose_name='Short Description'),
        ),
    ]
